### ISSUE TITLE
Is `mul128` going to be as fast as widening multiplication?

### ISSUE THREAD

**Issue by mitschabaude** [WebAssembly/128-bit-arithmetic#11]
First of all, congrats to this proposal!

Some background on why I think it will be useful: Widening multiplication 64 x 64 -> 128 is _the_ main bottleneck in all algorithms related to elliptic curve-based cryptography. That's because elliptic curves are defined over finite fields of size (typically) ~256 bits.

256-bit elements are represented as [64 64 64 64], and multiplication (and modular reduction) of two such elements is a central algorithm which always ends up being the critical bottleneck in EC cryptography.
When multiplying two 64-bit limbs, we need to get both halves of the result, i.e. an i128.

The missing Wasm support of this operation so far has led to significant slowdown compared to native when naively compiling standard algorithms. (See e.g. some documentation of that in [this write-up](https://github.com/mitschabaude/montgomery/blob/main/doc/zprize22.md)).

So, this proposal is promising to make Wasm implementation of EC-based crypto both simpler and faster.

My question is regarding the choice to expose `i64.mul128 : [128 128] -> 128` instead of `i64.mul_wide : [64 64] -> 128`. This choice is discussed in the proposal under [Alternative: Widening multiplication](https://github.com/WebAssembly/128-bit-arithmetic/blob/main/proposals/128-bit-arithmetic/Overview.md#alternative-widening-multiplication).

Quoting:
> The i64.mul_wide_u instruction can be encoded as i64.mul128 with constant 0 values for the upper bits and i64.mul_wide_s can be encoded similarly with a right-shift of the low bits. This means that i64.mul128 should be sufficient for expressing the use cases of i64.mul_wide_{s,u}.

So, I wanted to confirm that emulating `mul_wide` with inputs to `mul128` of the form [64 0], [64 0] is going to be compiled into instructions with no slow-down compared to a direct `mul_wide` instruction? (I'm not very familiar with compilers so please school me if this is obvious)

Clearly, for EC cryptography, only `mul_wide` is needed and not `mul128` so having maximal speed for `mul_wide`-type use cases is important.

**Comment by mitschabaude** [comment]
Awesome thanks, that's very promising!

I don't have a relevant benchmark at my fingertips but will come back with one when I get to it.

It will probably just be multiplying field elements or adding curve points with [arkworks](https://github.com/arkworks-rs/algebra/tree/master/ff) which is a pretty widely used library in my industry

**Comment by alexcrichton** [comment]
Some numbers in https://github.com/WebAssembly/128-bit-arithmetic/issues/6#issuecomment-2329985356 surprised me where mul128 was slower than mul_wide_u. Upon investigating I think I'd like to shift this proposal to using `i64.mul_wide_{u,s}` instead of `i64.mul128`.

The basic problem was that `i64.mul128` was selected as an instruction by LLVM even if the upper half of the result wasn't actually used. I believe that this all gets optimized away in native backends but such optimizations weren't in the wasm backend. This wasn't a problem with `i64.mul_wide_{u,s}` in the wasm backend though because I think that "fit better" with what LLVM already supports and it would naturally skip the `i64.mul_wide_{u,s}` if the high bits weren't necessary.

This is then additionally coupled with the fact that to achieve performance parity I've had to implement a number of pattern-matching optimizations such as:

* For `i64.mul128` if both operands are zero-extended from 64-bits then behave like `i64.mul_wide_u`
* For `i64.mul128` if both operands are sign-extended from 64-bits then behave like `i64.mul_wide_s`
* If the upper bits of one operand is a constant 0 then you can constant fold some of the component operations away because multiplication by zero is zero.

I tried to implement an optimization in the LLVM lowering to use `i64.mul` instead of `i64.mul128` when the upper bits weren't actually used, but while it worked for simple cases it didn't work in the benchmark I was looking at.

Overall this makes me lean in the direction of `i64.mul128` is requiring too much work to retain parity with `i64.mul_wide_{u,s}`. At this point the main motivation for `i64.mul128` was that it performed similarly and "felt cleaner" with the other 128-bit operations. The "performed similarly" point is now being proven wrong and I don't personally think the "feels cleaner" point continues to justify its existence.

Given all that I will likely make a PR to switch to `i64.mul_wide_{u,s}` instead of `i64.mul128`.

**Comment by alexcrichton** [comment]
I've opened https://github.com/WebAssembly/128-bit-arithmetic/pull/13 to replace `i64.mul128` with `i64.mul_wide_{s,u}`, some explanation of what those instructions are, and additionally some extra rationale.
